### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by ibnabbas** [geissbuehler/TermservPatcher#8] opened 2022-05-21 04:51 UTC
I am getting error as below:

Error: No match in termsrv.dll found for manual patch patterns
Scheduled task 'TermsrvPatcher' added (requires valid patches in 'Patches.txt', logging to 'UnattendLog.txt')

Patcher Version - 1.3.0

termsrv.dll Version: 10.0.19041.1

**Comment by geissbuehler** [comment] 2022-07-15 12:57
Duplicate of #1

**Closed as completed** 2022-07-15 12:58 UTC
Labels: duplicate, wontfix
